name: Deploy Main

on:
  push:
    branches: [ "main" ]

env:
  APPLICATION_NAME: "emby-recap"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set image tag
      id: tag
      run: echo "::set-output name=tag::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $APPLICATION_NAME:${{ steps.tag.outputs.tag }}

    - name: Export Docker image to archive
      run: docker save --output "$APPLICATION_NAME.tar.gz" $APPLICATION_NAME:${{ steps.tag.outputs.tag }}

    - name: Copy image to own infrastructure
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "${{ env.APPLICATION_NAME }}.tar.gz"
        target: "${{ env.APPLICATION_NAME }}"
        
    - name: Deploy to own infrastructure
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load < "${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.tar.gz"
          docker tag "${{ env.APPLICATION_NAME }}:${{ steps.tag.outputs.tag }}" "${{ env.APPLICATION_NAME }}:latest"
          docker compose --project-directory "${{ env.APPLICATION_NAME }}" up -d
